// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/models/model_quantized.onnx"
    | "/models/vocab.txt"
    | "/popup.html"
    | "/wasm/ort-wasm-simd-threaded.jsep.mjs"
    | "/wasm/ort-wasm-simd-threaded.jsep.wasm"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
